version: '3'
services:
  gateway:
    build: ./gateway
    restart: always
    hostname: gateway
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - backend
  token:
    build: ./token
    restart: always
    hostname: token
    ports:
      - ${TOKEN_SERVICE_PORT}:${TOKEN_SERVICE_PORT}
    env_file:
      - .env
    networks:
      - backend
  mailer:
    build: ./mailer
    restart: always
    hostname: mailer
    ports:
      - ${MAILER_SERVICE_PORT}:${MAILER_SERVICE_PORT}
    env_file:
      - .env
    networks:
      - backend
  user:
    build: ./user
    restart: always
    hostname: user
    ports:
      - ${USER_SERVICE_PORT}:${USER_SERVICE_PORT}
    env_file:
      - .env
    networks:
      - backend
    links:
      - mailer
networks:
  backend:
    driver: bridge
